name: Weather App CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: reem2244/weather-app

jobs:
  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

  deploy:
    name: Deploy Container on VM
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: SSH to VM and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Remove old container if running..."
            docker stop weather-app || true
            docker rm weather-app || true

            echo "Pulling latest image..."
            docker pull ${{ env.IMAGE_NAME }}:latest

            echo "Starting new container (weather-app)..."
            docker run -d -p 5000:5000 --name weather-app ${{ env.IMAGE_NAME }}:latest
